# travis.yml for R projects
language: r

sudo: false
warnings_are_errors: false
cache: packages

# codecov test coverage
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'
